language: java
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
      - ssh_known_hosts:47.99.204.53

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('12301') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
  -
  - openssl aes-256-cbc -K $encrypted_b69481b66723_key -iv $encrypted_b69481b66723_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa


jdk:
 - openjdk7

branchs:
  only:
    - master

install:  mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: true

after_success:
  # 登录服务器，执行部署脚本，其实最好把后面一串写成 shell 文件
  - ssh xxxshi@47.99.204.53 -o StrictHostKeyChecking=no 'cd /developer/ && ./seckill.sh master tomcat7_1'

