language: java
jdk:
- openjdk8
branchs:
  only:
  - master


script: true
after_success:
- ssh xxxshi@47.99.204.53 -o StrictHostKeyChecking=no 'cd /developer/ && ./seckill.sh
  master tomcat7_1'
addons:
  ssh_known_hosts: 47.99.204.53

