language: java
jdk:
- openjdk8
branchs:
  only:
  - master
script: true

  # ssh免密登录修改下面的代码：


after_success:
  # 登录服务器，执行部署脚本
  - ssh xxxshi@47.99.204.53 -o StrictHostKeyChecking=no 'cd /developer/ && ./seckill.sh
  master tomcat7_1'
addons:
  # 因为 travis 第一次登录远程服务器会出现 SSH 主机验证，这边会有一个主机信任问题。官方给出的方案是添加 addons 配置：
  ssh_known_hosts: 47.99.204.53

