language: java
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
    ssh_known_hosts:
      - 47.99.204.53

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('12301') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"

  - sudo service mysql restart

    # 因为我们把 id_rsa.enc 移到了.travis 文件夹下，所以 -in 后面要改成 .travis/id_rsa.enc
    # 其次，-out 后面自动生成的是 ~\/.ssh/id_rsa，要把 \ 去掉，否则会编译失败
    - openssl aes-256-cbc -K $encrypted_b69481b66723_key -iv $encrypted_b69481b66723_iv
      -in id_rsa.enc -out ~\/.ssh/id_rsa -d

    # 开启 ssh-agent，即允许使用 ssh 命令
    - eval "$(ssh-agent -s)"
    # 给予 id_rsa 文件权限，避免警告
    - chmod 600 ~/.ssh/id_rsa
    # 将私钥添加到 ssh
    - ssh-add ~/.ssh/id_rsa

jdk:
 - openjdk8

branchs:
  only:
    - master

install:  mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: - ssh xxxshi@47.99.204.53 -o StrictHostKeyChecking=no 'cd /developer/ && ./seckill.sh master tomcat7_1'

after_success:
  # 登录服务器，执行部署脚本，其实最好把后面一串写成 shell 文件
  - ssh xxxshi@47.99.204.53 -o StrictHostKeyChecking=no 'cd /developer/ && ./seckill.sh master tomcat7_1'

